;; generated by vcard-christianjaeger

(require vcard-easy lib/hide)

(def (cjcard)
     (vcard-easy-string
      given-name:
      "Christian"
      family-name:
      "Jaeger"
      nickname:
      "pflanze"
      tel-home:
      #f
      tel-mobile:
      #f
      email:
      (unhide "2DD279ACE820201DBC08251148218B2F08F3814F5C" 500 13/11)
      address-work:
      #f
      tz:
      "+00:00"
      role:
      "president"
      org:
      "Leaf Pair Ltd."
      uid:
      "fzfqz26bb5qn2getr3spcesyqc"
      url-preferred:
      personal
      url-preferred-pgpkey:
      personal
      url-personal:
      "http://christianjaeger.ch/"
      url-work:
      "http://leafpair.com/"
      public?:
      #t
      openpgp-fingerprint:
      "B222 CF68 5BF6 054D 0211  97CB 08FE FD1B 3039 B4ED"
      openpgp-source:
      url
      show-time-in-timestamp?:
      #f))
