;; generated by vcard-christianjaeger

(require vcard-easy lib/hide)

(def (cjcard)
     (vcard-easy-string
      given-name:
      "Christian"
      family-name:
      "Jaeger"
      nickname:
      "pflanze"
      tel-home:
      #f
      tel-mobile:
      #f
      email:
      (unhide "2DD279ACE820201DBC08251148218B2F08F3814F5C" 500 13/11)
      address-work:
      #f
      tz:
      "+00:00"
      role:
      "president"
      org:
      "Leaf Pair Ltd."
      uid:
      "fzfqz26bb5qn2getr3spcesyqc"
      url-preferred:
      personal
      url-preferred-pgpkey:
      personal
      url-personal:
      "http://christianjaeger.ch/"
      url-work:
      "http://leafpair.com/"
      public?:
      #t
      openpgp-fingerprint:
      "A54A 1D7C A1F9 4C86 6AC8  1A1F 0FA5 B211 04ED B072"
      openpgp-source:
      url
      show-time-in-timestamp?:
      #f))
